### ISSUE TITLE
Need Dockable Windows Demo

### ISSUE THREAD

**Issue by Richard-Tang** [bobbylight/FifeCommon#8]
Can you provide a demo? :)

Sorry I can't how to use `Dockable Windows`

**Comment by Richard-Tang** [comment]
:) I found an even simpler [project](https://github.com/bobbylight/Edisen)，It's a good example。https://github.com/bobbylight/Edisen

**Comment by bobbylight** [comment]
@Richard-Tang wow, I didn't think anyone used this repo except me :)

Edisen is a great project to base your work off of, though be forewarned:  it's using FifeCommon SNAPSHOTs in Sonatype.  As I'm building out Edisen (too slowly), I'm finding little ways FifeCommon could be better, and I'm integrating them into SNAPSHOTs as I go.  Thus things may change quickly there (the next FifeCommon posted to Maven Central should be 5.0.0 due to API changes, mostly around dockable windows, app preferences and simplifications of app themes).

As long as you're aware of that - glad you're up and running!
